// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvojdvgthulnzftnsctv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52b2pkdmd0aHVsbnpmdG5zY3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjY2MDUsImV4cCI6MjA3MzEwMjYwNX0.qHpgvCyFi1Z0ZxjJIx1roT8SKuhwdJyqhfBSXXaHMgU";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);