// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiiuvtoqxrqhzvgvzwxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpaXV2dG9xeHJxaHp2Z3Z6d3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Nzg2ODcsImV4cCI6MjA3MjE1NDY4N30.TE8P6S325HPJWBCsvSBu6pyYRklVI5u7E9YgOK3HdmI";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);